- name: Add Visual Studio Code to repo on Fedora
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: no

- name: Install Visual Studio Code on Fedora
  become: yes
  yum:
    name: code
    state: present

- name: Install DBeaver on Fedora
  become: yes
  yum:
    name: https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm
    state: present
  when: dbeaver is defined and dbeaver == "true"

- name: Install Vivaldi on Fedora
  become: yes
  yum:
    name: https://downloads.vivaldi.com/stable/vivaldi-stable-2.6.1566.44-1.x86_64.rpm