---
- name: Install VSCode on Ubuntu
  become: yes
  shell: snap install --classic code

- name: Install DBeaver on Ubuntu
  become: yes
  shell: snap install --edge dbeaver-ce

- name: Install Vivaldi Browser on Ubuntu
  become: yes
  tasks:
  - name: Get the APT key
    apt_key:
      url: http://repo.vivaldi.com/stable/linux_signing_key.pub
      state: present

  - name: Add to repository
    apt_repository:
        repo: deb http://repo.vivaldi.com/stable/deb/ stable main
        state: present
    
  - name: Install the browser
    apt:
      name: vivaldi-stable
      state: present