---
- name: Install VSCode on Ubuntu
  become: yes
  shell: snap install --classic code

- name: Install DBeaver on Ubuntu
  become: yes
  shell: snap install --edge dbeaver-ce

- name: Install Brave Browser on Ubuntu
  become: yes
  shell: snap install brave