---
- name: Install networking packages
  import_tasks: install_networking.yml

- name: Install all other packages
  import_tasks: install_misc.yml

- name: Install VSCode & DBeaver
  import_tasks: Fedora/install_packages.yml
  when: ansible_distribution == "Fedora"

- name: Install programming packages
  import_tasks: install_development.yml

- name: Install VSCode & DBeaver
  import_tasks: Ubuntu/install_packages.yml
  when: ansible_distribution == "Ubuntu"
