---
- name: Install networking packages
  import_tasks: commons/install_networking.yml

- name: Install all other packages
  import_tasks: commons/install_misc.yml

- name: Install VSCode, Dbeaver, Telegram and gcloud
  import_tasks: Fedora/install_packages.yml
  when: ansible_distribution == "Fedora"

- name: Install programming packages
  import_tasks: commons/install_development.yml

- name: Install VSCode & DBeaver
  import_tasks: Ubuntu/install_packages.yml
  when: ansible_distribution == "Ubuntu"

- name: Install zsh
  import_tasks: zsh/install.yml
  when: zsh is defined and zsh == "true"

- name: Install devops packages
  import_tasks: commons/install_devops.yml
  when: devops is defined and devops == "true"
