---
- include_vars: " {{ item }}"
  with_first_found:
    - "../../vars/{{ ansible_distribution }}/packages_networking.yml"

- name: Install networking related packages on {{ ansible_distribution }}
  become: yes
  package:
    name: "{{ pkg }}"
    state: present

