---
- include_vars: " {{ item }}"
  with_first_found:
    - "../../vars/{{ ansible_distribution }}/packages_devops.yml"

- name: Install Devops packages on {{ ansible_distribution }}
  become: yes
  package:
    name: "{{ pkg }}"
    state: present

- name: Install Helm v3 client
  become: yes
  unarchive:
    src: https://get.helm.sh/helm-v3.0.3-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/helm'
    remote_src: True

- name: Install k9s client
  become: yes
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.13.6/k9s_0.13.6_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    extra_opts:
    - --wildcards
    - 'k9s'
    remote_src: True

- name: Install Azure/AWS cli clients
  pip:
    name:
      - azure-cli
      - awscli
    extra_args: --user
