---
- include_vars: " {{ item }}"
  with_first_found:
    - "../../vars/{{ ansible_distribution }}/packages_development.yml"

- name: Install development related packages on {{ ansible_distribution }}
  become: yes
  package:
    name="{{ pkg }}"
    state=present
    use=auto

